CREATE DATABASE Proyecto_POO_DB;
USE Proyecto_DB_POO;
SET LANGUAGE 'us_english';

CREATE TABLE MANAGER(
	Id INT PRIMARY KEY,
	username VARCHAR (30)NOT NULL,
	password_manager VARCHAR (30) NOT NULL,
	id_cabin INT NOT NULL
);
--
CREATE TABLE EMPLOYEE(
	Id INT PRIMARY KEY IDENTITY,
	full_name VARCHAR (30) NOT NULL,
	institutional_mail VARCHAR (25) NOT NULL,
	Employee_address VARCHAR (50) NOT NULL,
	id_type INT NOT NULL,
	id_cabin INT NOT NULL
);

ALTER TABLE EMPLOYEE ALTER COLUMN id_type INT NOT NULL
--
CREATE TABLE REGISTER(
	Id INT PRIMARY KEY IDENTITY,
	date_cabine DATETIME,
	id_manager INT,
	id_cabin INT
);
--	

CREATE TABLE CABIN(
	Id INT PRIMARY KEY IDENTITY,
	address_cabin VARCHAR(50) NOT NULL,
	cabin_phone VARCHAR(9) NOT NULL,
	Manager VARCHAR(50),
	Email VARCHAR(50) NOT NULL
);

--	

CREATE TABLE APPOINTMENT(
	 Id INT PRIMARY KEY IDENTITY,
     First_date DATETIME,
	 Second_date DATETIME,
	 Vaccination_place VARCHAR(50) NOT NULL,
	 id_cabin INT,
	 Dui VARCHAR(10)
);
--
CREATE TABLE CITIZEN(
	Dui VARCHAR(10) PRIMARY KEY,
	Full_name VARCHAR(50) NOT NULL,
	Citizen_address VARCHAR(100) NOT NULL,
	phone_number VARCHAR(9) NOT NULL,
	Email VARCHAR(40),
	Age INT NOT NULL,
	Id_Charge INT,
	Id_Sec_Effect INT,
	Id_Record INT,
	Id_Disease INT,
	Date_Vaccine DATETIME,
	Date_Arrival DATETIME
);
--
CREATE TABLE DISEASE(
	Id INT PRIMARY KEY IDENTITY,
	Disease_Name VARCHAR(30) NOT NULL,
);


CREATE TABLE CHARGE(
Id INT PRIMARY KEY IDENTITY,
Name_Charge VARCHAR(30) NOT NULL
);

CREATE TABLE SECONDARY_EFFECT(
Id INT PRIMARY KEY IDENTITY,
SEC_EFFECT VARCHAR(30) NOT NULL
);

CREATE TABLE TYPE_(
Id INT PRIMARY KEY IDENTITY,
Type_Employee VARCHAR(30) NOT NULL
);

CREATE TABLE CABINxCITIZEN(
	Dui VARCHAR(10) NOT NULL,
	Id_Cabin int NOT NULL	
);


-- CREATE FK

ALTER TABLE REGISTER ADD FOREIGN KEY (id_cabin) REFERENCES CABIN (id)
ALTER TABLE REGISTER ADD FOREIGN KEY (id_manager) REFERENCES MANAGER (id)

ALTER TABLE MANAGER ADD FOREIGN KEY (id_cabin) REFERENCES CABIN (id)

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (id_cabin) REFERENCES CABIN (id)
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (id_type) REFERENCES TYPE_ (id)

ALTER TABLE CITIZEN ADD FOREIGN KEY (id_Charge) REFERENCES CHARGE (id)

ALTER TABLE CITIZEN ADD FOREIGN KEY (id_Sec_Effect) REFERENCES SECONDARY_EFFECT (id)

ALTER TABLE CITIZEN ADD FOREIGN KEY (Id_Disease) REFERENCES DISEASE (Id)

ALTER TABLE APPOINTMENT ADD FOREIGN KEY (id_cabin) REFERENCES CABIN (id)
ALTER TABLE APPOINTMENT ADD FOREIGN KEY (Dui) REFERENCES CITIZEN (dui)

ALTER TABLE CABINxCITIZEN ADD PRIMARY KEY (dui,id_cabin);
ALTER TABLE CABINxCITIZEN ADD FOREIGN KEY (dui) REFERENCES CITIZEN (dui)
ALTER TABLE CABINxCITIZEN ADD FOREIGN KEY (id_cabin) REFERENCES CABIN (id)

---- BANCO DE DATOS----
--TABLE CABIN
INSERT INTO CABIN VALUES ('Santa tecla, Parque San Martín', '2278-3698','Marcelo Bran','cabina1@covid.sv');
INSERT INTO CABIN VALUES ('Santa Ana, Alcaldia Municipal', '2556-7891','Axel Hernandez','cabina2@covid.sv');
INSERT INTO CABIN VALUES ('La Libertad, Puerto de la Libertad', '2556-9911','Javier Alfredo','cabina3@covid.sv');
INSERT INTO CABIN VALUES ('Apaneca,Parque Central', '2278-3377','Kevin Duran','cabina4@covid.sv');
SELECT * FROM CABIN;

--TABLE CHARGE
INSERT INTO CHARGE VALUES ('Personal de salud');
INSERT INTO CHARGE VALUES ('PNC');
INSERT INTO CHARGE VALUES ('Fuerza Armada');
INSERT INTO CHARGE VALUES ('Cuerpos de socorro');
INSERT INTO CHARGE VALUES ('Personal de fronteras');
INSERT INTO CHARGE VALUES ('Personal de centros penales');
INSERT INTO CHARGE VALUES ('Personal del gobierno central');
SELECT * FROM CHARGE;

--TABLE DISEASE
INSERT INTO DISEASE VALUES ('Cancer');
INSERT INTO DISEASE VALUES ('Diabetes');
INSERT INTO DISEASE VALUES ('Artritis');
INSERT INTO DISEASE VALUES ('Asma');
INSERT INTO DISEASE VALUES ('Enfermedad del corazón');
INSERT INTO DISEASE VALUES ('VIH-SIDA');
INSERT INTO DISEASE VALUES ('Esclerosis Múltiple');
INSERT INTO DISEASE VALUES ('Otros.');
SELECT * FROM DISEASE;

--TABLE SECONDARY_EFFECT
INSERT INTO SECONDARY_EFFECT VALUES ( 'Dolor de brazo');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Enrojecimiento de brazo');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Fatiga');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Dolor de cabeza');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Fiebre');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Mialgia');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Atralgia');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Anafilaxia');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Otros');
INSERT INTO SECONDARY_EFFECT VALUES ( 'Ninguna.');
SELECT * FROM SECONDARY_EFFECT;
--TABLE TYPE_
INSERT INTO TYPE_ VALUES('Gestor')
INSERT INTO TYPE_ VALUES('Asistente de Salud')
INSERT INTO TYPE_ VALUES('Vacunador')
SELECT * FROM TYPE_;

--TABLE MANAGER
INSERT INTO MANAGER VALUES(1,'AxelJ','contra10',2)
INSERT INTO MANAGER VALUES(2,'JavierA','contra11',3)
INSERT INTO MANAGER VALUES(3,'MarceloB','contra9',1)
INSERT INTO MANAGER VALUES(4,'KevinD','contra12',4)

--TABLE EMPLOYEE

INSERT INTO EMPLOYEE VALUES('Alejandro Cuellar','AleC1213@gmail.com','Ciudad merliot,Sabana-B#12',2,10)
INSERT INTO EMPLOYEE VALUES('Jorge Garcia','JGarcia88@gmail.com','Av, Las colinas, Res Guadalupe #22',3,1)
INSERT INTO EMPLOYEE VALUES('Isaac Quezada','IsaacGrande2211@gmail.com','Lourdes Colon, Las Arboleras #1',2,2)
INSERT INTO EMPLOYEE VALUES('Kevin Joel','Kots2020@gmail.com','Residencial los sueños #122, La libertad ',3,2)
INSERT INTO EMPLOYEE VALUES('Diego Garcia','Rocko_12@gmail.com','Col. Quezaltepec, santa tecla',2,3)
INSERT INTO EMPLOYEE VALUES('Ariana Vanegas','Kots2020@gmail.com','Col.Palo Alto casa#44, La libertad ',3,3)
INSERT INTO EMPLOYEE VALUES('Mauricio Canizales','Maurilol45@gmail.com','Col. La maravilla #98, Santa Ana',3,4)
INSERT INTO EMPLOYEE VALUES('Nuria Chavez','NuryChav@gmail.com','Res. El valle #77, Santa Ana',2,4)

select * from EMPLOYEE
delete CITIZEN where Age = 18
